//Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
//1,2,3,5,8,13,21,34,55,89
//By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms

#include <iostream>
using namespace std;
int main()
{
	unsigned int a=1;
	unsigned int b=2;
	unsigned int next=a+b;
	int i=1;
	long long evenSum=2;
	long long checkSum=2;
	while(next<4000000)
	{
		if(next%2==0)
		{
			evenSum+=next;
		}
		a=b;
		b=next;
		next=a+b;
		
		
		/*
		alt code based on idea that even number must appear every third index, "checkSum".
		*/
		i++;
		if(i%3==0)
		{
			cout << i << ": ";
			checkSum+=next;
		}
	}	
	cout << evenSum << endl;
	cout << "CheckSum: " << checkSum << endl;
}

